name: Workflow Filters and Activities
on:
  workflow_dispatch:
  push:
    # branches-ignore:
    #   - 'feature/*'
    #   - 'test/**'
    branches:
      - 'main'
      - '!feature/*'
  pull-request:
    types:
      - opened
      - closed
    paths-ignore:
      - README.md
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: echo step
        run: echo this worklfow/job/step is executed for ${{ github.event_name }}

    
    


